# Generated by Django 3.0.8 on 2020-11-21 19:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
import notes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=30)),
                ('desc', models.CharField(default='', max_length=1000)),
                ('upload_time', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='upload_time')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=notes.models.thumbnail_uploadto_path)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail', to='notes.Note')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('datetime', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='reviewed_time')),
                ('score', models.FloatField(default=0)),
                ('text', models.TextField(max_length=1000)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='notes.Note')),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(related_name='notes', to='notes.Tag'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('image', models.ImageField(upload_to=notes.models.image_uploadto_path)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='notes.Note')),
            ],
        ),
    ]
