# Generated by Django 3.0.1 on 2020-01-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20200116_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='upload_time',
            field=models.DateTimeField(null=True, verbose_name='upload_time'),
        ),
    ]
