# Generated by Django 3.0.1 on 2020-01-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20200128_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='desc',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='note',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
