# Generated by Django 3.0.1 on 2020-01-17 18:20

from django.db import migrations, models
import notes.models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_remove_note_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=notes.models.note_directory_path),
        ),
    ]
