# Generated by Django 3.0.1 on 2020-01-31 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20200131_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tag',
            field=models.ManyToManyField(related_name='notes', to='notes.Tag'),
        ),
        migrations.AlterField(
            model_name='note',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='upload_time'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
