# Generated by Django 3.0.2 on 2020-02-17 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_note_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='subject',
        ),
    ]
