# Generated by Django 3.0.1 on 2020-02-19 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_remove_note_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='tag',
            new_name='tags',
        ),
    ]
