# Generated by Django 3.0.1 on 2020-02-26 17:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_auto_20200219_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='notes.Note'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('datetime', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='reviewed_time')),
                ('score', models.FloatField()),
                ('text', models.TextField(max_length=1000)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='notes.Note')),
            ],
        ),
    ]
