# Generated by Django 3.0.1 on 2020-02-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0013_auto_20200227_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='mean_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
